# Generated by Django 4.2 on 2023-04-12 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_message"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="room",),
        migrations.AddField(
            model_name="message",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.project",
            ),
        ),
    ]
