# Generated by Django 4.2 on 2023-04-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_alter_message_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="name",
            field=models.CharField(default="SOME STRING", max_length=20),
        ),
    ]
