# Generated by Django 4.2 on 2023-04-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_message_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="name",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
